# Generated by Django 4.2.7 on 2025-03-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('restaurant', 'Restaurant'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
