# Generated by Django 4.2.7 on 2025-03-01 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='count',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='stamp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Redemption',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
