# Generated by Django 4.2.7 on 2025-03-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='restaurant',
            field=models.CharField(default='Default Restaurant', max_length=100),
        ),
    ]
