# Generated by Django 4.2.7 on 2025-04-09 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalLoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('backgroud_image', models.ImageField(null=True, upload_to='')),
                ('slot_number', models.IntegerField(default=0)),
                ('slot_image', models.ImageField(null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='reward',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reward',
            name='stamp_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Stamp',
        ),
        migrations.AddField(
            model_name='customerreward',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loyalty.digitalloyaltycard'),
            preserve_default=False,
        ),
    ]
