# Generated by Django 4.2.7 on 2025-04-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_digitalloyaltycard_remove_reward_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalloyaltycard',
            name='name',
            field=models.CharField( max_length=255),
        ),
        migrations.AddField(
            model_name='reward',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loyalty.digitalloyaltycard'),
            preserve_default=False,
        ),
    ]
