# Generated by Django 4.2.7 on 2025-04-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_userdigitalcard_stamptransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamptransaction',
            name='stamp',
            field=models.IntegerField(default=0),
        ),
    ]
