# Generated by Django 4.2.7 on 2025-04-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_stamptransaction_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalloyaltycard',
            old_name='backgroud_image',
            new_name='background_image',
        ),
        migrations.AlterField(
            model_name='reward',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='loyalty.digitalloyaltycard'),
        ),
    ]
