# Generated by Django 4.2.7 on 2025-04-21 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_rename_backgroud_image_digitalloyaltycard_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stamptransaction',
            old_name='customer',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='customerreward',
            name='card',
        ),
        migrations.RemoveField(
            model_name='customerreward',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='stamptransaction',
            name='stamp',
        ),
        migrations.AddField(
            model_name='customerreward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerreward',
            name='reward_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='user_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loyalty.userdigitalcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stamptransaction',
            name='is_reward_slot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stamptransaction',
            name='stamped',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='assigned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stamptransaction',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.userdigitalcard'),
        ),
    ]
