# Generated by Django 4.2.7 on 2025-04-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_rename_customer_stamptransaction_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreward',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.stamptransaction'),
        ),
    ]
