# Generated by Django 4.2.7 on 2025-04-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_menuitem_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
    ]
