# Generated by Django 4.2.7 on 2025-04-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_review_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('parking_available', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=20)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='restaurant.restaurant')),
            ],
        ),
    ]
