# Generated by Django 4.2.7 on 2025-04-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurantdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
