# Generated by Django 4.2.7 on 2025-04-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('kitchen', 'In Kitchen'), ('served', 'Served')], default='pending', max_length=20),
        ),
    ]
