# Generated by Django 4.2.7 on 2025-04-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_kot_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
    ]
